const resObj = [
  {
    id: 1,
    name: "Pizza Hut",
    cuisine: "Pizza",
    rating: 4.2,
    deliveryTime: "30 mins",
  },
  {
    id: 2,
    name: "Dominos",
    cuisine: "Pizza",
    rating: 4.0,
    deliveryTime: "25 mins",
  },
  {
    id: 3,
    name: "McDonald's",
    cuisine: "Burger",
    rating: 3.3,
    deliveryTime: "20 mins",
  },
  {
    id: 4,
    name: "KFC",
    cuisine: "Fried Chicken",
    rating: 4.1,
    deliveryTime: "28 mins",
  },
  {
    id: 5,
    name: "Burger King",
    cuisine: "Burger",
    rating: 4.0,
    deliveryTime: "22 mins",
  },
  {
    id: 6,
    name: "Haldiram's",
    cuisine: "Indian",

    rating: 4.5,
    deliveryTime: "35 mins",
  },
  {
    id: 7,
    name: "Biryani Blues",
    cuisine: "Biryani",
    rating: 4.4,
    deliveryTime: "40 mins",
  },
  {
    id: 8,
    name: "Behrouz Biryani",
    cuisine: "Biryani",
    rating: 3.3,
    deliveryTime: "38 mins",
  },
  {
    id: 9,
    name: "Subway",
    cuisine: "Sandwich",
    rating: 3.2,
    deliveryTime: "18 mins",
  },
  {
    id: 10,
    name: "WOW! Momo",
    cuisine: "Momos",
    rating: 4.1,
    deliveryTime: "20 mins",
  },
  {
    id: 11,
    name: "Chai Sutta Bar",
    cuisine: "Tea & Snacks",
    rating: 4.0,
    deliveryTime: "15 mins",
  },
  {
    id: 12,
    name: "La Pino'z Pizza",
    cuisine: "Pizza",
    rating: 3.3,
    deliveryTime: "27 mins",
  },
  {
    id: 13,
    name: "Bikanervala",
    cuisine: "Indian Sweets",
    rating: 3.4,
    deliveryTime: "30 mins",
  },
  {
    id: 14,
    name: "Giani's Ice Cream",
    cuisine: "Dessert",
    rating: 3.5,
    deliveryTime: "15 mins",
  },
  {
    id: 15,
    name: "The Belgian Waffle Co.",
    cuisine: "Waffles",
    rating: 3.6,
    deliveryTime: "20 mins",
  },
   {
    id: 16,
    name: "The Nisbelgium Wifuifle Co.",
    cuisine: "Waffles fst",
    rating: 3.9,
    deliveryTime: "21 mins",
  },
];

export default resObj;